---
name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.4.0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.test.txt
          pip install -r requirements.txt
          pip list
      - name: Pytest with coverage reporting
        run: pytest --cov=sharkiq --cov-report=xml
      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.9 && matrix.os == 'ubuntu'
        uses: codecov/codecov-action@v5.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
